### ISSUE TITLE
IDE lesson could be more toned down/objective/factual

### ISSUE THREAD

**Issue by krishnakumarg1984** [carpentries-incubator/python-intermediate-development#145]
Warning:  This issue is about a very subjective perception, (but could be worth having a think anyway)?

The lesson on IDEs has a strongly upbeat tone. In the text, I felt subtle undercurrents glorifying modern IDEs. While I have nothing against IDEs, the knowledge doesn't translate well into certain scientific scenarios e.g. HPC development on remote machines, which is a cornerstone of modern computational science, which typically don't explicitly offer an X11 or Wayland session by default.

Editing code on the login node of a remote machine with a graphical desktop/X-forwarding will be an underwhelming experience.

A properly configured (neo)vim or emacs can serve as a proper replacement for IDEs, atleast in the academic/research space. A good editor paired to a language server can usually be sufficient, providing a snappy editing experience on remote machines.

**Comment by anenadic** [comment]
We do actually work in command line in the course for most of the time (e.g. when interacting with GitHub via Git) but feel that most of our audience tend to use an IDE for their work - hence the reason to cover setting things up from an IDE. Getting people to learn to use vim/emacs for this course would be a cognitive overload since, from experience, our audience is still on the beginner spectrum but tend to have experience with IDEs.
