### ISSUE TITLE
pycharm changes?

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/python-intermediate-development#166]
I don't see the same "No interpreter configured" warnings as listed in the [section 1 ide episode](https://carpentries-incubator.github.io/python-intermediate-development/13-ides/index.html).  Also when I go to set the interpreter, it is still "Settings" instead of preferences for me on my mac.  Maybe updates to pycharm are causing differences?

**Comment by sstevens2** [comment]
I guess I didn't get the error because it guessed it should use the venv?  when I looked in preferences it was already set to use the venv and didn't say blank or the default interpreter.

**Comment by sstevens2** [comment]
Also listed in [section 1 - pep8 episode](https://carpentries-incubator.github.io/python-intermediate-development/15-coding-conventions/index.html) as "Preferences" in the indentation section

**Comment by sstevens2** [comment]
Also seems like the "show whitespace" option mentioned in that episode has moved - https://www.jetbrains.com/help/pycharm/settings-editor-appearance.html

**Comment by anenadic** [comment]
OK, so I had a look and more recent version of PyCharm on Mac are using "Settings" instead of "Preferences" option (even though the pop up window is still called "Preferences"). This and the whitespaces option being moved to a different location have now been addressed in #288.

The "No interpreter configured" option will only show if no Python interpreter has even been configured in PyCharm and I suspect you has it configured at some point in the past @sstevens2? I confirmed very recently (a week or two ago) that this "No interpreter configured" option still show up on a brand new PyCharm installation where not Python has been pervasively configured. Hope this fixes this issue @sstevens2? Will close after #288 is merged.

**Comment by sstevens2** [comment]
Sorry I'm not sure if I have any answers on it @anenadic.  I don't use pycharm so I didn't have it configured in any specific way.  Maybe something with out it detects python if you have anaconda also installed?  Happy for you to close though and address if it comes up for others in the future.
