### ISSUE TITLE
Pycharm 'show whitespace' option has moved

### ISSUE THREAD

**Issue by gcapes** [carpentries-incubator/python-intermediate-development#245]
At least using PyCharm 2023.1.3 (Professional Edition) it's now under settings:
https://www.jetbrains.com/help/pycharm/settings-editor-appearance.html
![image](https://github.com/carpentries-incubator/python-intermediate-development/assets/12446270/d72ee8b3-0cea-4cae-a795-ca8be019e949)

**Comment by anenadic** [comment]
Thank you @gcapes. The issue appears in episode on [coding conventions](https://carpentries-incubator.github.io/python-intermediate-development/15-coding-conventions/index.html). I can confirm this is also the case in PyCharm Community Edition 2021. Instead of View > Active Editor> Show whitespaces it should be Settings > Editor > General > Appearance. Would you be able to do a PR to fix this issue @gcapes ?
